### PR TITLE
Forecast issue 866 (new forecast.ss input options)

### PR DESCRIPTION
**Pull request by iantaylor-NOAA**
@e-gugliotti-NOAA, I'm mostly on leave today and tomorrow but wanted to push the progress I made on this issue yesterday for you to look over if you have time.

Of the three SS3 issues, only one required changes, I think.
* [Issue #487](https://github.com/nmfs-stock-synthesis/stock-synthesis/issues/487) No change needed (input/output is the same, but multiplier is no longer ignored within SS3 when using Forecast Recruitment option 4)
* [Issue #490](https://github.com/nmfs-stock-synthesis/stock-synthesis/issues/490) Looks like these changes got folded into issue 493, I don't see differences in forecast.ss but might be missing something.
* [Issue #493](https://github.com/nmfs-stock-synthesis/stock-synthesis/issues/493) Changes made to read/write functions in commits 092d6a2 and 797d785.

I tested using the attached files in [forecast_3.30.22_test.zip](https://github.com/r4ss/r4ss/files/12821555/forecast_3.30.22_test.zip) with the beta version of 3.30.22 from the github action archive. I was able to successfully read and write the forecast file with the new input format as well as run SS3 on the written file and also re-read the written file back into r4ss.

Note: I don't think that the new input format triggered by the -12345 in the first value of the forecast years input is described in the User Manual yet. I can help with that next week.

### CODE REVIEW

**Comment by iantaylor-NOAA** [comment]
Sorry, I should have rebased this branch before issuing the pull request. I went ahead and merged main into it, creating a messier commit history, but hopefully resolving any issues.

**Comment by e-gugliotti-NOAA** [comment]
Thanks, Ian for pushing this! I'll give this a look later today.

**Comment by e-gugliotti-NOAA** [comment]
I invoked the new format in one of the test model files (vermillion snapper) and tried SS_read and I get the following error
```Warning message:
In r4ss::SS_readforecast(file = file.path(dir, ifelse(ss_new, "forecast.ss_new",  :
  Error: final value is 2 but should be 999
```
This could be me doing something wrong but I'm not sure.

**Comment by iantaylor-NOAA** [comment]
@e-gugliotti-NOAA, thanks for the additional testing. Can you send me (or attached to this pull request) the file you used which caused the error?

**Comment by iantaylor-NOAA** [comment]
The vermillion snapper forecast had some extra lines associated with the old input format. The modified file (.txt extension added to facilitate attaching in github) [forecast.ss.txt](https://github.com/r4ss/r4ss/files/12860825/forecast.ss.txt) runs in the current main branch of SS3 and works with the `forecast_issue_866` branch of r4ss.

**Comment by e-gugliotti-NOAA** [comment]
Oh great! I figured it might be something like that that I happened to miss but just wanted to make sure!

**Comment by e-gugliotti-NOAA** [comment]
@iantaylor-NOAA Do you think it would be worth adding something in the ss3 text and user manual to not use those options with the new format?

**Review by e-gugliotti-NOAA — APPROVED** [review]

**Pull request merged**
