### PR TITLE
Use updated ghactions4r workflow in r4ss

### PR DESCRIPTION
**Pull request by e-perl-NOAA**
See issue #981.

### CODE REVIEW

**Comment by e-perl-NOAA** [comment]
This branch had some attempts to work on another issue but those were reverted and all the commits will just be squashed when merged.

**Comment by e-perl-NOAA** [comment]
It's still failing because of the change to the get_ss3_exe() function to not use tokens in the gh::gh() call. With github actions, the same runner for mac is used so it calls the api enough times that the github api gets mad. I have no idea how to fix it for github actions. I tried several things but didn't get anywhere.

**Comment by iantaylor-NOAA** [comment]
The fix in #986 should have this PR work fine now, but it looks like we should change the `@add-additional-args-to-yaml` to back to `@main` now that the branch has been merged in https://github.com/nmfs-fish-tools/ghactions4r/pull/147, right?

**Comment by e-perl-NOAA** [comment]
Sorry @iantaylor-NOAA I didn't realize that I hadn't changed that back to main but that's why we have these reviews!

**Comment by e-perl-NOAA** [comment]
It might still fail because it's using the github action from this branch, not the one from main. I would need to rebase this branch to get it passing all the checks which I can do if you would like.

**Pull request merged**
