### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by nathanvaughan-NOAA**
These two commits correct a couple of bugs that came up working with a recent assessment due to additional options added to SS.

### CODE REVIEW

**Review by iantaylor-NOAA — APPROVED** [review]
@nathanvaughan-NOAA, thanks for providing this fix. 

Could you add a comment above the new line 208 in `SS_readpar_3.30()` to explain what that line is doing because the logic is a bit convoluted (in part due to the `[[""]]` notation applied by the automatic styling).

Is it just filtering out any F parameter that don't have phase 99 (which maybe get added by the newer F method 4)?

I'm on leave all next week so leave it to @e-perl-NOAA to merge if all the tests are passing.

**Comment by nathanvaughan-NOAA** [comment]
Thanks Ian will do. Yes it is just filtering out only catches for fleets that have a none 99 phase to determine how many F parameters there should be.

**Comment by nathanvaughan-NOAA** [comment]
Added a descriptive comment which helped me realize this would have broken for F_method=2 so added a check that the F_4_Fleet_Parms object exists before using it to subset catch. Have a great week off, see you when you get back!

**Comment by iantaylor-NOAA** [comment]
Thanks @nathanvaughan-NOAA. 
The github actions would probably have caught that issue because it runs `SS_readpar_3.30()` on a bunch of test models (in https://github.com/r4ss/r4ss/blob/main/tests/testthat/test-readwrite.R#L52-L56), but for reasons that I don't understand those extra tests take 4 hours (discussed #950), and it's a good idea to wait until they finish for a change like this, so merging will have to wait until next week after we confirm that things are working.

**Pull request merged**
