### PR TITLE
fix(SS_tune_comps): MI_mult for agecomps is wrong in SS 3.30.12-16

### PR DESCRIPTION
**Pull request by kellijohnson-NOAA**
QUESTIONS: 
* can someone check my proposed math in this commit to
ensure that I got the tuning correct?
* also, now that I created the pull request I remembered that
I only tested this with age comps; can someone check that I didn't
break things for length comps?

recommended variance adjustment is wrong b/c it was set to 1.0.
@iantaylor-noaa knows and is fixing it in SS but r4ss will still
need to work with this output for 12-16 models.

Updated documentation based on ability to use markdown in the file,
which makes things easier to read, moved some sections.

Noticed during the 2021 pacific hake stock assessment

### CODE REVIEW

**Comment by k-doering-NOAA** [comment]
The tests in https://github.com/r4ss/r4ss/blob/development/tests/testthat/test-tune_comps.R are run with the gh actions "run-tests-with-SS" job. It uses a length comps model. Kelli, are you concerned that the values aren't right for len comps, or just want to make sure it runs? I think these tests show you didn't introduce code that causes the function not to run. I can look in more detail at len comp weights produced if you think it is necessary.

**Comment by kellijohnson-NOAA** [comment]
I just wanted to provide the disclaimer that I might not have thought through all scenarios given I was only working with age data. Though, I just checked that with length data (copper rockfish 2021; thanks @chantelwetzel-noaa ) it gives you the same output as the Recommended_var_adj. I will note @k-doering-NOAA that your tests altered me to an earlier dumb commit that I got rid of with -f early this morning. So thank you for your providing those.

**Comment by kellijohnson-NOAA** [comment]
I pushed a new commit because using -f would get rid of my mistake and the context of this discussion on markdown would seem weird. So, I will leave my mistake documented for eternity :(

**Comment by iantaylor-NOAA** [comment]
Checks have passed, seems adequately tested on copper example. Thanks @kellijohnson-NOAA.

**Pull request merged**
