### PR TITLE
Fixes for reading and writing control and data files from more complex models

### PR DESCRIPTION
**Pull request by k-doering-NOAA**
This PR contains:
- Fixes in order to make it possible to read and write more complex control and data files using r4ss functions. In total, control files from 25 models were tested, many of which were production assessment models. Hopefully, this will expand the range of models that work with the r4ss read and write functions.
- Some formatting cleanup. This includes removing unnecessary comments, commented out code, whitespace, and also some formatting changes to headers to make the recognizable to rstudio as headers.

### CODE REVIEW

**Comment by k-doering-NOAA** [comment]
Update: I am planning on adding a few more small changes to this PR before it is merged in.

**Comment by k-doering-NOAA** [comment]
Changes made, so reopening this request.

**Comment by iantaylor-NOAA** [comment]
Thanks @k-doering-NOAA for all this work

**Comment by iantaylor-NOAA** [comment]
Note: commit 1668ca8a2c5a2cc6d2c1a9caa353c191a3a84a12 updates the documentation for the readctl files (to reflect additional argument `N_dirichlet_parms = 0`).

I've also just incremented the version number to 1.37.0 in the development branch since there have been many changes over the past week and this will help users keep track of whether they've successfully installed the updated package.

**Pull request merged**
