### PR TITLE
Issues #442 and #399

### PR DESCRIPTION
**Pull request by k-doering-NOAA**
Addresses #442 and #399 (removing dollar sign subsetting, which allows for partial matching, and use styler to get consistent styling for the r4ss source code).

### CODE REVIEW

**Comment by iantaylor-NOAA** [comment]
Thanks @k-doering-NOAA. It will be great to have this more robust and cleaned-up code going forward.
Let's confirm tomorrow that the checks have passed and then merge this pull request.

**Comment by k-doering-NOAA** [comment]
Sounds good! One thing I should mention is if the dollar sign was intentionally used to allow partial matching, then the "cleanup" would cause the code to break. I think this situation should be pretty rare, though...

**Comment by k-doering-NOAA** [comment]
@iantaylor-NOAA , I think this is ready to be merged. commit 43b5a53 was pushed to fix code that worked with partial matching before (I think only needed by models with tagging data) that was converted to not work with partial matching. I think partial matching was used just for convince?

We might catch a few more bugs like this where partial matching was used, but I think these issues will be few and far between.

**Comment by iantaylor-NOAA** [comment]
Thanks for all this work, @k-doering-NOAA. As discussed offline, I'm merging after one more minor change and we'll wait for the tests to re-run on the merged development branch.

**Pull request merged**
