### PR TITLE
Fix spr series in SS_output() and get_SIS_info() to handle two table approach in SS3

### PR DESCRIPTION
**Pull request by e-perl-NOAA**
See SS3 PR [#609](https://github.com/nmfs-ost/ss3-source-code/pull/609) for changes in SS3 report file that needed to be changed in r4ss.

### CODE REVIEW

**Comment by iantaylor-NOAA** [comment]
Thanks for working on this. I have a few changes to add but need a little more time to implement them so will push them to the branch tomorrow.

**Comment by iantaylor-NOAA** [comment]
I ran the checks locally within this branch using the latest SS3 exe from the GHA artifact and got 10 failures. I can work on debugging these later today. Not sure if they are all related to the modified SPR table or other recent changes.

```
r$> devtools::test()
i Testing r4ss
v | F W  S  OK | Context
v |         28 | Basic r4ss functions [20.7s]
v |          8 | Read and write SS control file r4ss functions [17.3s]
/ |          0 | download_models
trying URL 'https://github.com/nmfs-ost/ss3-test-models/archive/main.zip'
downloaded 715 KB

- |          1 | download_models
trying URL 'https://github.com/nmfs-ost/ss3-test-models/archive/main.zip'
downloaded 715 KB

/ |          4 | download_models
trying URL 'https://github.com/nmfs-ost/ss3-test-models/archive/main.zip'
Content type 'application/zip' length 732362 bytes (715 KB)
downloaded 715 KB

v |          2 | Run get_SIS_info() on simple_small model output [1.1s]
/ |          0 | get_ss3_exe                                                                                                             trying URL 
'https://github.com/nmfs-ost/ss3-source-code/releases/download/v3.30.22.1/ss3_win.exe'
Content type 'application/octet-stream' length 7374847 bytes (7.0 MB)
downloaded 7.0 MB

- |          1 | get_ss3_exe                                                                                                             trying URL 
'https://github.com/nmfs-ost/ss3-source-code/releases/download/v3.30.18/ss3_win.exe'
trying URL 'https://github.com/nmfs-ost/ss3-source-code/releases/download/v3.30.18/ss_win.exe'
Content type 'application/octet-stream' length 7289082 bytes (7.0 MB)
downloaded 7.0 MB

\ |          2 | get_ss3_exe                                                                                                             trying URL 
'https://github.com/nmfs-ost/ss3-source-code/releases/download/v3.30.22.1/ss3_win.exe'
Content type 'application/octet-stream' length 7374847 bytes (7.0 MB)
downloaded 7.0 MB

/ |          4 | get_ss3_exe                                                                                                             trying URL 
'https://github.com/nmfs-ost/ss3-source-code/releases/download/v3.30.22.1/ss3_win.exe'
Content type 'application/octet-stream' length 7374847 bytes (7.0 MB)
downloaded 7.0 MB

v |          6 | get_ss3_exe [80.2s]
v |   9      5 | Basic r4ss functions [64.3s]
----------------------------------------------------------------------------------------------------------------------------------------------------Warning (test-older_ss3.R:63:3): SSsummarize and SSplotComparisons work to compare 3.24 to 3.30
problem summarizing growth due to different accumulator ages among models
Backtrace:
    x
 1. \-r4ss::SSsummarize(list(simple3.24, simple_small)) at test-older_ss3.R:63:3

Warning (test-older_ss3.R:63:3): SSsummarize and SSplotComparisons work to compare 3.24 to 3.30
problem summarizing age selectivity due to mismatched columns (perhaps different bins)

Backtrace:
    x
 1. \-r4ss::SSsummarize(list(simple3.24, simple_small)) at test-older_ss3.R:63:3

Warning (test-older_ss3.R:66:3): SSsummarize and SSplotComparisons work to compare 3.24 to 3.30
setting btarg = -999 because models don't have matching values
Backtrace:
    x
 1. \-r4ss::SSplotComparisons(...) at test-older_ss3.R:66:3

Warning (test-older_ss3.R:66:3): SSsummarize and SSplotComparisons work to compare 3.24 to 3.30
setting minbthresh = -999 because models don't have matching values
Backtrace:
    x
 1. \-r4ss::SSplotComparisons(...) at test-older_ss3.R:66:3

Warning (test-older_ss3.R:66:3): SSsummarize and SSplotComparisons work to compare 3.24 to 3.30
setting sprtarg = -999 because models don't have matching values
Backtrace:
    x
 1. \-r4ss::SSplotComparisons(...) at test-older_ss3.R:66:3

Warning (test-older_ss3.R:66:3): SSsummarize and SSplotComparisons work to compare 3.24 to 3.30
setting label for SPR plot to 8th element of input 'labels' because the models don't have matching labels
Backtrace:
    x
 1. \-r4ss::SSplotComparisons(...) at test-older_ss3.R:66:3

Warning (test-older_ss3.R:66:3): SSsummarize and SSplotComparisons work to compare 3.24 to 3.30
setting label for F plot to 13th element of input 'labels' because the models don't have matching labels
Backtrace:
    x
 1. \-r4ss::SSplotComparisons(...) at test-older_ss3.R:66:3

Warning (test-older_ss3.R:66:3): SSsummarize and SSplotComparisons work to compare 3.24 to 3.30
zero-length arrow is of indeterminate angle and so skipped
Backtrace:
    x
 1. \-r4ss::SSplotComparisons(...) at test-older_ss3.R:66:3
 2.   \-r4ss (local) plotRecruits() at r4ss/R/SSplotComparisons.R:2401:11
 3.     \-graphics::arrows(...) at r4ss/R/SSplotComparisons.R:1437:15

Warning (test-older_ss3.R:66:3): SSsummarize and SSplotComparisons work to compare 3.24 to 3.30
zero-length arrow is of indeterminate angle and so skipped
Backtrace:
    x
 1. \-r4ss::SSplotComparisons(...) at test-older_ss3.R:66:3
 2.   \-grDevices::dev.off() at r4ss/R/SSplotComparisons.R:2406:11
----------------------------------------------------------------------------------------------------------------------------------------------------v |          2 | Test read and write par functions [12.0s]
v |          2 | plotCI
x | 2       81 | populate_multiple_folders [2.3s]
----------------------------------------------------------------------------------------------------------------------------------------------------Failure (test-populate_multiple_folders.R:23:5): populate_multiple_folders runs
list.files(file.path(temp_path, d)) has length 5, not length 4.
Backtrace:
    x
 1. \-base::lapply(...) at test-populate_multiple_folders.R:21:3
 2.   \-r4ss (local) FUN(X[[i]], ...)
 3.     \-testthat::expect_length(...) at test-populate_multiple_folders.R:23:5

Failure (test-populate_multiple_folders.R:23:5): populate_multiple_folders runs
list.files(file.path(temp_path, d)) has length 5, not length 4.
Backtrace:
    x
 1. \-base::lapply(...) at test-populate_multiple_folders.R:21:3
 2.   \-r4ss (local) FUN(X[[i]], ...)
 3.     \-testthat::expect_length(...) at test-populate_multiple_folders.R:23:5
----------------------------------------------------------------------------------------------------------------------------------------------------v |          8 | Profiling and changing parameter values
v |   2    329 | Generalized read and write function tests [34.8s]
----------------------------------------------------------------------------------------------------------------------------------------------------Warning (test-readwrite.R:50:5): models can be read and written
Duplicate lambda input for likelihood component(s): 4, 4; fleet(s): 1, 1; phase(s):1, 1
Backtrace:
    x
 1. \-r4ss::SS_readctl(file.path(m, start[["ctlfile"]]), datlist = dat) at test-readwrite.R:50:5
 2.   \-r4ss::SS_readctl_3.30(...) at r4ss/R/SS_readctl.R:144:5

Warning (test-readwrite.R:64:5): models can be read and written
Duplicate lambda input for likelihood component(s): 4, 4; fleet(s): 1, 1; phase(s):1, 1
Backtrace:
    x
 1. \-r4ss::SS_read(m) at test-readwrite.R:64:5
 2.   \-r4ss::SS_readctl(...) at r4ss/R/SS_read.R:78:3
 3.     \-r4ss::SS_readctl_3.30(...) at r4ss/R/SS_readctl.R:144:5
----------------------------------------------------------------------------------------------------------------------------------------------------| | 1 5      5 | r4ss functions that require executables to run                                                                          likesaved
754.302 
      2
\ | 1 8      5 | r4ss functions that require executables to run                                                                          likesaved
754.302 
      2
x | 3 13     12 | r4ss functions that require executables to run [244.0s]
----------------------------------------------------------------------------------------------------------------------------------------------------Warning (test-runs.R:45:3): retro() and populate_multiple_folders() both work
Copying multiple executable files
Backtrace:
     x
  1. \-r4ss::retro(...) at test-runs.R:45:3
  2.   \-furrr::future_walk(...) at r4ss/R/retro.R:121:3
  3.     \-furrr:::furrr_map_template(...)
  4.       \-furrr:::furrr_template(...)
  5.         +-future::value(futures)
  6.         \-future:::value.list(futures)
  7.           +-future::resolve(...)
  8.           \-future:::resolve.list(...)
  9.             \-future (local) signalConditionsASAP(obj, resignal = FALSE, pos = ii)
 10.               \-future:::signalConditions(...)

Warning (test-runs.R:45:3): retro() and populate_multiple_folders() both work
Copying multiple executable files
Backtrace:
     x
  1. \-r4ss::retro(...) at test-runs.R:45:3
  2.   \-furrr::future_walk(...) at r4ss/R/retro.R:121:3
  3.     \-furrr:::furrr_map_template(...)
  4.       \-furrr:::furrr_template(...)
  5.         +-future::value(futures)
  6.         \-future:::value.list(futures)
  7.           +-future::resolve(...)
  8.           \-future:::resolve.list(...)
  9.             \-future (local) signalConditionsASAP(obj, resignal = FALSE, pos = ii)
 10.               \-future:::signalConditions(...)

Warning (test-runs.R:45:3): retro() and populate_multiple_folders() both work
Copying multiple executable files
Backtrace:
     x
  1. \-r4ss::retro(...) at test-runs.R:45:3
  2.   \-furrr::future_walk(...) at r4ss/R/retro.R:121:3
  3.     \-furrr:::furrr_map_template(...)
  4.       \-furrr:::furrr_template(...)
  5.         +-future::value(futures)
  6.         \-future:::value.list(futures)
  7.           +-future::resolve(...)
  8.           \-future:::resolve.list(...)
  9.             \-future (local) signalConditionsASAP(obj, resignal = FALSE, pos = ii)
 10.               \-future:::signalConditions(...)

Error (test-runs.R:63:3): retro() and populate_multiple_folders() both work
Error in ``[[<-.data.frame`(`*tmp*`, "Yr", value = numeric(0))`: replacement has 0 rows, data has 1
Backtrace:
    x
 1. \-r4ss::SSgetoutput(...) at test-runs.R:63:3
 2.   \-r4ss::SS_output(...) at r4ss/R/SSgetoutput.R:114:9
 3.     +-base::`[[<-`(`*tmp*`, "Yr", value = `<dbl>`) at r4ss/R/SS_output.R:2896:7
 4.     \-base::`[[<-.data.frame`(`*tmp*`, "Yr", value = `<dbl>`) at r4ss/R/SS_output.R:2896:7

Warning (test-runs.R:125:3): jitter runs on simple_small model
Copying multiple executable files
Backtrace:
    x
 1. +-testthat::expect_true(...) at test-runs.R:125:3
 2. | \-testthat::quasi_label(enquo(object), label, arg = "object")
 3. |   \-rlang::eval_bare(expr, quo_get_env(quo))
 4. \-r4ss::copy_SS_inputs(...)

Warning (test-runs.R:148:5): jitter runs on simple_small model
Copying multiple executable files
Backtrace:
     x
  1. \-r4ss::jitter(...) at test-runs.R:148:5
  2.   \-furrr::future_map_dbl(...) at r4ss/R/jitter.R:181:3
  3.     \-furrr:::furrr_map_template(...)
  4.       \-furrr:::furrr_template(...)
  5.         +-future::value(futures)
  6.         \-future:::value.list(futures)
  7.           +-future::resolve(...)
  8.           \-future:::resolve.list(...)
  9.             \-future (local) signalConditionsASAP(obj, resignal = FALSE, pos = ii)
 10.               \-future:::signalConditions(...)

Warning (test-runs.R:148:5): jitter runs on simple_small model
Copying multiple executable files
Backtrace:
     x
  1. \-r4ss::jitter(...) at test-runs.R:148:5
  2.   \-furrr::future_map_dbl(...) at r4ss/R/jitter.R:181:3
  3.     \-furrr:::furrr_map_template(...)
  4.       \-furrr:::furrr_template(...)
  5.         +-future::value(futures)
  6.         \-future:::value.list(futures)
  7.           +-future::resolve(...)
  8.           \-future:::resolve.list(...)
  9.             \-future (local) signalConditionsASAP(obj, resignal = FALSE, pos = ii)
 10.               \-future:::signalConditions(...)

Warning (test-runs.R:156:5): jitter runs on simple_small model
Copying multiple executable files
Backtrace:
     x
  1. \-r4ss::jitter(...) at test-runs.R:156:5
  2.   \-furrr::future_map_dbl(...) at r4ss/R/jitter.R:181:3
  3.     \-furrr:::furrr_map_template(...)
  4.       \-furrr:::furrr_template(...)
  5.         +-future::value(futures)
  6.         \-future:::value.list(futures)
  7.           +-future::resolve(...)
  8.           \-future:::resolve.list(...)
  9.             \-future (local) signalConditionsASAP(obj, resignal = FALSE, pos = ii)
 10.               \-future:::signalConditions(...)

Warning (test-runs.R:156:5): jitter runs on simple_small model
Copying multiple executable files
Backtrace:
     x
  1. \-r4ss::jitter(...) at test-runs.R:156:5
  2.   \-furrr::future_map_dbl(...) at r4ss/R/jitter.R:181:3
  3.     \-furrr:::furrr_map_template(...)
  4.       \-furrr:::furrr_template(...)
  5.         +-future::value(futures)
  6.         \-future:::value.list(futures)
  7.           +-future::resolve(...)
  8.           \-future:::resolve.list(...)
  9.             \-future (local) signalConditionsASAP(obj, resignal = FALSE, pos = ii)
 10.               \-future:::signalConditions(...)

Error (test-runs.R:172:5): jitter runs on simple_small model
Error in ``[[<-.data.frame`(`*tmp*`, "Yr", value = numeric(0))`: replacement has 0 rows, data has 1
Backtrace:
    x
 1. \-r4ss::SSgetoutput(dir.jit, keyvec = c(1:2)) at test-runs.R:172:5
 2.   \-r4ss::SS_output(...) at r4ss/R/SSgetoutput.R:114:9
 3.     +-base::`[[<-`(`*tmp*`, "Yr", value = `<dbl>`) at r4ss/R/SS_output.R:2896:7
 4.     \-base::`[[<-.data.frame`(`*tmp*`, "Yr", value = `<dbl>`) at r4ss/R/SS_output.R:2896:7

Warning (test-runs.R:191:3): profile functions run on simple_small model
Copying multiple executable files
Backtrace:
    x
 1. \-r4ss::copy_SS_inputs(...) at test-runs.R:191:3

Warning (test-runs.R:208:3): profile functions run on simple_small model
Copying multiple executable files
Backtrace:
     x
  1. \-r4ss::profile(...) at test-runs.R:208:3
  2.   \-furrr::future_map(...) at r4ss/R/profile.R:439:3
  3.     \-furrr:::furrr_map_template(...)
  4.       \-furrr:::furrr_template(...)
  5.         +-future::value(futures)
  6.         \-future:::value.list(futures)
  7.           +-future::resolve(...)
  8.           \-future:::resolve.list(...)
  9.             \-future (local) signalConditionsASAP(obj, resignal = FALSE, pos = ii)
 10.               \-future:::signalConditions(...)

Warning (test-runs.R:208:3): profile functions run on simple_small model
Copying multiple executable files
Backtrace:
     x
  1. \-r4ss::profile(...) at test-runs.R:208:3
  2.   \-furrr::future_map(...) at r4ss/R/profile.R:439:3
  3.     \-furrr:::furrr_map_template(...)
  4.       \-furrr:::furrr_template(...)
  5.         +-future::value(futures)
  6.         \-future:::value.list(futures)
  7.           +-future::resolve(...)
  8.           \-future:::resolve.list(...)
  9.             \-future (local) signalConditionsASAP(obj, resignal = FALSE, pos = ii)
 10.               \-future:::signalConditions(...)

Warning (test-runs.R:216:3): profile functions run on simple_small model
32 estimated parameters indicated by the par file
  31 estimated parameters shown in the covar file
  Returning the par file value: 32
Backtrace:
    x
 1. \-r4ss::SSgetoutput(dirvec = dir.prof, keyvec = 1:2) at test-runs.R:216:3
 2.   \-r4ss::SS_output(...) at r4ss/R/SSgetoutput.R:114:9

Error (test-runs.R:216:3): profile functions run on simple_small model
Error in ``[[<-.data.frame`(`*tmp*`, "Yr", value = numeric(0))`: replacement has 0 rows, data has 1
Backtrace:
    x
 1. \-r4ss::SSgetoutput(dirvec = dir.prof, keyvec = 1:2) at test-runs.R:216:3
 2.   \-r4ss::SS_output(...) at r4ss/R/SSgetoutput.R:114:9
 3.     +-base::`[[<-`(`*tmp*`, "Yr", value = `<dbl>`) at r4ss/R/SS_output.R:2896:7
 4.     \-base::`[[<-.data.frame`(`*tmp*`, "Yr", value = `<dbl>`) at r4ss/R/SS_output.R:2896:7

Warning (test-runs.R:239:3): Run an SS3 model and read the hessian
Copying multiple executable files
Backtrace:
    x
 1. \-r4ss::copy_SS_inputs(...) at test-runs.R:239:3
----------------------------------------------------------------------------------------------------------------------------------------------------v |          1 | Run SSexecutivesummary on model output [1.1s]
x | 1        0 | Read output and make plots for all test-models [51.2s]
----------------------------------------------------------------------------------------------------------------------------------------------------Error (test-test-models.R:55:3): test-models work with SS_output() and SS_plots()
<purrr_error_indexed/rlang_error/error/condition>
Error in `(function (.x, .f, ..., .progress = FALSE)
{
    map_("list", .x, .f, ..., .progress = .progress)
})(.x = c("C:\\Users\\IAN~1.TAY\\AppData\\Local\\Temp\\RtmpqotoHt/test-test-models/models/BigSkate_2019",
"C:\\Users\\IAN~1.TAY\\AppData\\Local\\Temp\\RtmpqotoHt/test-test-models/models/Empirical_Wtatage_Age_Selex"
), .f = function (...)
{
    NULL
    NULL
    ...furrr_out <- ...furrr_fn(...)
    ...furrr_out
})`: i In index: 1.
Caused by error in `[[<-.data.frame`:
! replacement has 0 rows, data has 1
Backtrace:
     x
  1. +-parallel (local) workRSOCK()
  2. | \-parallel:::workLoop(...)
  3. |   \-parallel:::workCommand(master)
  4. |     +-base::tryCatch(...)
  5. |     | \-base (local) tryCatchList(expr, classes, parentenv, handlers)
  6. |     |   \-base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
  7. |     |     \-base (local) doTryCatch(return(expr), name, parentenv, handler)
  8. |     +-base::tryCatch(...)
  9. |     | \-base (local) tryCatchList(expr, classes, parentenv, handlers)
 10. |     |   \-base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 11. |     |     \-base (local) doTryCatch(return(expr), name, parentenv, handler)
 12. |     +-base::do.call(msg$data$fun, msg$data$args, quote = TRUE)
 13. |     \-future (local) `<fn>`(...)
 14. |       \-base::eval(expr, envir = envir, enclos = enclos)
 15. |         \-base::eval(expr, envir = envir, enclos = enclos)
 16. +-base::tryCatch(...)
 17. | \-base (local) tryCatchList(expr, classes, parentenv, handlers)
 18. |   \-base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 19. |     \-base (local) doTryCatch(return(expr), name, parentenv, handler)
 20. +-base::withCallingHandlers(...)
 21. +-base::withVisible(...)
 22. +-base::local(...)
 23. | \-base::eval.parent(substitute(eval(quote(expr), envir)))
 24. |   \-base::eval(expr, p)
 25. |     \-base::eval(expr, p)
 26. +-base::eval(...)
 27. | \-base::eval(...)
 28. |   +-base::withCallingHandlers(...)
 29. |   +-base::do.call(...furrr_map_fn, args)
 30. |   \-purrr (local) `<fn>`(.x = `<chr>`, .f = `<fn>`)
 31. |     \-purrr:::map_("list", .x, .f, ..., .progress = .progress)
 32. |       +-purrr:::with_indexed_errors(...)
 33. |       | \-base::withCallingHandlers(...)
 34. |       +-purrr:::call_with_cleanup(...)
 35. |       \-.f(.x[[i]], ...)
 36. |         \-r4ss (local) ...furrr_fn(...)
 37. |           \-r4ss::SS_output(x, verbose = FALSE, printstats = FALSE) at test-test-models.R:61:7
 38. |             +-base::`[[<-`(`*tmp*`, "Yr", value = `<dbl>`)
 39. |             \-base::`[[<-.data.frame`(`*tmp*`, "Yr", value = `<dbl>`)
 40. |               \-base::stop(...)
 41. \-base::.handleSimpleError(...)
 42.   \-purrr (local) h(simpleError(msg, call))
 43.     \-cli::cli_abort(...)
 44.       \-rlang::abort(...)
----------------------------------------------------------------------------------------------------------------------------------------------------v |          1 | TSCplot
/ |   1      7 | Test the tune_comps function                                                                                            Error in `[[<-.data.frame`(`*tmp*`, "Yr", value = numeric(0)) :
  replacement has 0 rows, data has 1
- | 1 1      7 | Test the tune_comps function                                                                                            Error in `[[<-.data.frame`(`*tmp*`, "Yr", value = numeric(0)) :
  replacement has 0 rows, data has 1
\ | 2 1      7 | Test the tune_comps function                                                                                            Error in `[[<-.data.frame`(`*tmp*`, "Yr", value = numeric(0)) :
  replacement has 0 rows, data has 1
| | 3 1      7 | Test the tune_comps function                                                                                            Error in `[[<-.data.frame`(`*tmp*`, "Yr", value = numeric(0)) :
  replacement has 0 rows, data has 1
x | 4 1      7 | Test the tune_comps function [27.3s]
----------------------------------------------------------------------------------------------------------------------------------------------------Warning (test-tune_comps.R:72:3): tune_comps() works with francis
ss_win.log does not contain information on the size of temporary files.
Backtrace:
    x
 1. \-r4ss::tune_comps(...) at test-tune_comps.R:72:3
 2.   +-base::try(...) at r4ss/R/tune_comps.R:237:5
 3.   | \-base::tryCatch(...)
 4.   |   \-base (local) tryCatchList(expr, classes, parentenv, handlers)
 5.   |     \-base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 6.   |       \-base (local) doTryCatch(return(expr), name, parentenv, handler)
 7.   \-r4ss::SS_output(...)

Error (test-tune_comps.R:88:3): tune_comps() works with MI and up tuning
Error in `tune_comps(replist = NULL, fleets = "all", option = "MI", niters_tuning = 1,
    init_run = FALSE, dir = file.path(runs_path, "simple_small"),
    allow_up_tuning = TRUE, verbose = FALSE)`: Please specify replist (no report file found) or set init_run == TRUE when using option Francis, MI, 
or none
Backtrace:
    x
 1. \-r4ss::tune_comps(...) at test-tune_comps.R:88:3

Error (test-tune_comps.R:104:3): tune_comps() works with DM
Error in ``[[<-.data.frame`(`*tmp*`, "Yr", value = numeric(0))`: replacement has 0 rows, data has 1
Backtrace:
    x
 1. \-r4ss::tune_comps(...) at test-tune_comps.R:104:3
 2.   +-base::suppressWarnings(...) at r4ss/R/tune_comps.R:527:7
 3.   | \-base::withCallingHandlers(...)
 4.   \-r4ss::SS_output(...)
 5.     +-base::`[[<-`(`*tmp*`, "Yr", value = `<dbl>`) at r4ss/R/SS_output.R:2896:7
 6.     \-base::`[[<-.data.frame`(`*tmp*`, "Yr", value = `<dbl>`) at r4ss/R/SS_output.R:2896:7

Error (test-tune_comps.R:132:3): tune_comps() works with none
Error in `tune_comps(option = "none", dir = file.path(runs_path, "simple_small"),
    verbose = FALSE)`: Please specify replist (no report file found) or set init_run == TRUE when using option Francis, MI, or none
Backtrace:
    x
 1. \-r4ss::tune_comps(...) at test-tune_comps.R:132:3

Error (test-tune_comps.R:148:3): tune_comps() works with multiple iterations
Error in `tune_comps(replist = NULL, fleets = "all", option = "MI", niters_tuning = 2,
    init_run = FALSE, dir = file.path(runs_path, "simple_small"),
    allow_up_tuning = TRUE, verbose = FALSE)`: Please specify replist (no report file found) or set init_run == TRUE when using option Francis, MI, 
or none
Backtrace:
    x
 1. \-r4ss::tune_comps(...) at test-tune_comps.R:148:3
----------------------------------------------------------------------------------------------------------------------------------------------------
Maximum number of failures exceeded; quitting at end of file.
i Increase this number with (e.g.) `testthat::set_max_fails(Inf)` 

== Results =========================================================================================================================================
Duration: 569.2 s

-- Failed tests ------------------------------------------------------------------------------------------------------------------------------------Failure (test-populate_multiple_folders.R:23:5): populate_multiple_folders runs
list.files(file.path(temp_path, d)) has length 5, not length 4.
Backtrace:
    x
 1. \-base::lapply(...) at test-populate_multiple_folders.R:21:3
 2.   \-r4ss (local) FUN(X[[i]], ...)
 3.     \-testthat::expect_length(...) at test-populate_multiple_folders.R:23:5

Failure (test-populate_multiple_folders.R:23:5): populate_multiple_folders runs
list.files(file.path(temp_path, d)) has length 5, not length 4.
Backtrace:
    x
 1. \-base::lapply(...) at test-populate_multiple_folders.R:21:3
 2.   \-r4ss (local) FUN(X[[i]], ...)
 3.     \-testthat::expect_length(...) at test-populate_multiple_folders.R:23:5

Error (test-runs.R:63:3): retro() and populate_multiple_folders() both work
Error in ``[[<-.data.frame`(`*tmp*`, "Yr", value = numeric(0))`: replacement has 0 rows, data has 1
Backtrace:
    x
 1. \-r4ss::SSgetoutput(...) at test-runs.R:63:3
 2.   \-r4ss::SS_output(...) at r4ss/R/SSgetoutput.R:114:9
 3.     +-base::`[[<-`(`*tmp*`, "Yr", value = `<dbl>`) at r4ss/R/SS_output.R:2896:7
 4.     \-base::`[[<-.data.frame`(`*tmp*`, "Yr", value = `<dbl>`) at r4ss/R/SS_output.R:2896:7

Error (test-runs.R:172:5): jitter runs on simple_small model
Error in ``[[<-.data.frame`(`*tmp*`, "Yr", value = numeric(0))`: replacement has 0 rows, data has 1
Backtrace:
    x
 1. \-r4ss::SSgetoutput(dir.jit, keyvec = c(1:2)) at test-runs.R:172:5
 2.   \-r4ss::SS_output(...) at r4ss/R/SSgetoutput.R:114:9
 3.     +-base::`[[<-`(`*tmp*`, "Yr", value = `<dbl>`) at r4ss/R/SS_output.R:2896:7
 4.     \-base::`[[<-.data.frame`(`*tmp*`, "Yr", value = `<dbl>`) at r4ss/R/SS_output.R:2896:7

Error (test-runs.R:216:3): profile functions run on simple_small model
Error in ``[[<-.data.frame`(`*tmp*`, "Yr", value = numeric(0))`: replacement has 0 rows, data has 1
Backtrace:
    x
 1. \-r4ss::SSgetoutput(dirvec = dir.prof, keyvec = 1:2) at test-runs.R:216:3
 2.   \-r4ss::SS_output(...) at r4ss/R/SSgetoutput.R:114:9
 3.     +-base::`[[<-`(`*tmp*`, "Yr", value = `<dbl>`) at r4ss/R/SS_output.R:2896:7
 4.     \-base::`[[<-.data.frame`(`*tmp*`, "Yr", value = `<dbl>`) at r4ss/R/SS_output.R:2896:7

Error (test-test-models.R:55:3): test-models work with SS_output() and SS_plots()
<purrr_error_indexed/rlang_error/error/condition>
Error in `(function (.x, .f, ..., .progress = FALSE)
{
    map_("list", .x, .f, ..., .progress = .progress)
})(.x = c("C:\\Users\\IAN~1.TAY\\AppData\\Local\\Temp\\RtmpqotoHt/test-test-models/models/BigSkate_2019",
"C:\\Users\\IAN~1.TAY\\AppData\\Local\\Temp\\RtmpqotoHt/test-test-models/models/Empirical_Wtatage_Age_Selex"
), .f = function (...)
{
    NULL
    NULL
    ...furrr_out <- ...furrr_fn(...)
    ...furrr_out
})`: i In index: 1.
Caused by error in `[[<-.data.frame`:
! replacement has 0 rows, data has 1
Backtrace:
     x
  1. +-parallel (local) workRSOCK()
  2. | \-parallel:::workLoop(...)
  3. |   \-parallel:::workCommand(master)
  4. |     +-base::tryCatch(...)
  5. |     | \-base (local) tryCatchList(expr, classes, parentenv, handlers)
  6. |     |   \-base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
  7. |     |     \-base (local) doTryCatch(return(expr), name, parentenv, handler)
  8. |     +-base::tryCatch(...)
  9. |     | \-base (local) tryCatchList(expr, classes, parentenv, handlers)
 10. |     |   \-base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 11. |     |     \-base (local) doTryCatch(return(expr), name, parentenv, handler)
 12. |     +-base::do.call(msg$data$fun, msg$data$args, quote = TRUE)
 13. |     \-future (local) `<fn>`(...)
 14. |       \-base::eval(expr, envir = envir, enclos = enclos)
 15. |         \-base::eval(expr, envir = envir, enclos = enclos)
 16. +-base::tryCatch(...)
 17. | \-base (local) tryCatchList(expr, classes, parentenv, handlers)
 18. |   \-base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 19. |     \-base (local) doTryCatch(return(expr), name, parentenv, handler)
 20. +-base::withCallingHandlers(...)
 21. +-base::withVisible(...)
 22. +-base::local(...)
 23. | \-base::eval.parent(substitute(eval(quote(expr), envir)))
 24. |   \-base::eval(expr, p)
 25. |     \-base::eval(expr, p)
 26. +-base::eval(...)
 27. | \-base::eval(...)
 28. |   +-base::withCallingHandlers(...)
 29. |   +-base::do.call(...furrr_map_fn, args)
 30. |   \-purrr (local) `<fn>`(.x = `<chr>`, .f = `<fn>`)
 31. |     \-purrr:::map_("list", .x, .f, ..., .progress = .progress)
 32. |       +-purrr:::with_indexed_errors(...)
 33. |       | \-base::withCallingHandlers(...)
 34. |       +-purrr:::call_with_cleanup(...)
 35. |       \-.f(.x[[i]], ...)
 36. |         \-r4ss (local) ...furrr_fn(...)
 37. |           \-r4ss::SS_output(x, verbose = FALSE, printstats = FALSE) at test-test-models.R:61:7
 38. |             +-base::`[[<-`(`*tmp*`, "Yr", value = `<dbl>`)
 39. |             \-base::`[[<-.data.frame`(`*tmp*`, "Yr", value = `<dbl>`)
 40. |               \-base::stop(...)
 41. \-base::.handleSimpleError(...)
 42.   \-purrr (local) h(simpleError(msg, call))
 43.     \-cli::cli_abort(...)
 44.       \-rlang::abort(...)

Error (test-tune_comps.R:88:3): tune_comps() works with MI and up tuning
Error in `tune_comps(replist = NULL, fleets = "all", option = "MI", niters_tuning = 1,
    init_run = FALSE, dir = file.path(runs_path, "simple_small"),
    allow_up_tuning = TRUE, verbose = FALSE)`: Please specify replist (no report file found) or set init_run == TRUE when using option Francis, MI, 
or none
Backtrace:
    x
 1. \-r4ss::tune_comps(...) at test-tune_comps.R:88:3

Error (test-tune_comps.R:104:3): tune_comps() works with DM
Error in ``[[<-.data.frame`(`*tmp*`, "Yr", value = numeric(0))`: replacement has 0 rows, data has 1
Backtrace:
    x
 1. \-r4ss::tune_comps(...) at test-tune_comps.R:104:3
 2.   +-base::suppressWarnings(...) at r4ss/R/tune_comps.R:527:7
 3.   | \-base::withCallingHandlers(...)
 4.   \-r4ss::SS_output(...)
 5.     +-base::`[[<-`(`*tmp*`, "Yr", value = `<dbl>`) at r4ss/R/SS_output.R:2896:7
 6.     \-base::`[[<-.data.frame`(`*tmp*`, "Yr", value = `<dbl>`) at r4ss/R/SS_output.R:2896:7

Error (test-tune_comps.R:132:3): tune_comps() works with none
Error in `tune_comps(option = "none", dir = file.path(runs_path, "simple_small"),
    verbose = FALSE)`: Please specify replist (no report file found) or set init_run == TRUE when using option Francis, MI, or none
Backtrace:
    x
 1. \-r4ss::tune_comps(...) at test-tune_comps.R:132:3

Error (test-tune_comps.R:148:3): tune_comps() works with multiple iterations
Error in `tune_comps(replist = NULL, fleets = "all", option = "MI", niters_tuning = 2,
    init_run = FALSE, dir = file.path(runs_path, "simple_small"),
    allow_up_tuning = TRUE, verbose = FALSE)`: Please specify replist (no report file found) or set init_run == TRUE when using option Francis, MI, ancis, MI, or none
Backtrace:
    x
 1. \-r4ss::tune_comps(...) at test-tune_comps.R:148:3

[ FAIL 10 | WARN 25 | SKIP 0 | PASS 504 ]
== Terminated early ===========================================================================================================================================
```

**Comment by e-perl-NOAA** [comment]
At least for the first issue with the populate_multiple_folders it looks like its copying the wtatage.ss file which gives 5 files rather than 4 causing the issue because the test is expecting a length of 4. I feel like you would want the wtatage.ss file so maybe we should just change that testing for 4 or 5 files instead of just 4.

**Comment by e-perl-NOAA** [comment]
Thanks so much for working on this Ian!

**Comment by e-perl-NOAA** [comment]
Test with ss3 updates passed so it looks good to merge.

**Pull request merged**
