### PR TITLE
add token as NA to gh call in get_ss3_exe

### PR DESCRIPTION
**Pull request by e-perl-NOAA**
See [issue and resolution in gh package repository](https://github.com/r-lib/gh/issues/216). Resolves @efletcherPIFSC's [issue in ss3diags](https://github.com/PIFSCstockassessments/ss3diags/issues/109#issuecomment-2477541840).

### CODE REVIEW

**Review by iantaylor-NOAA — APPROVED** [review]
Thanks @e-perl-NOAA, @efletcherPIFSC, and all involved in finding this fix. I'm just going to merge immediately as there's nothing in the extra tests that would tell us more about this change.

**Comment by efletcherPIFSC** [comment]
Will this patch be available for r4ss 1.50.0 and 1.49.3 (pre read/write function changes) releases?

**Comment by iantaylor-NOAA** [comment]
@efletcherPIFSC, good point. We should issue a release/tag of 1.50.1 which includes this fix.

Making a release of the old version before the read/write changes seems convoluted. I think a cleaner solution would to copy the updated get_ss3_exe function into ss3diags until you have time to update the package to work with the current r4ss.

**Comment by efletcherPIFSC** [comment]
@iantaylor-NOAA 
In the intern, until ss3diags r4ss 1.50.0+ versions, I have a R script based on the `r4ss::get_ss3_exe` with the gh token fixes

**Pull request merged**
