### PR TITLE
Add capability to read data comments (lines starting from '#C') in da…

### PR DESCRIPTION
**Pull request by yukio-takeuchi**
In response to #479  this  pull request  adds capability to keep comments starting from "#C" to SS_readdat/ctl_3.30 and to include them into new dat/ctlfile to SS_writedat/ctl_3.30.
These codes pick up lines starting from #C above lines containing numeric values.
I also included a utility function (get_data_comments.r) for those work.  Potentially this new function can be used if comments starting from #C is needed to keep when starter.ss or forecast.ss are read by SS_readstarter or SS_readforecast. 

Since SS_writedat/ctl_3.30  write 2 or 3 comments lines with "#C" including   time stamp when new dat/ctlfile is written.  Revised SS_readdat/ctl_3.30 of this pull request will ignore them (i.e., they will not included either in datlist[["dataComments"]]  or ctllist[["dataComments"]] where comments with "#C" is stored. SS_writedat/ctl_3.30 will create new comments containing those information with "#C"

### CODE REVIEW

**Comment by iantaylor-NOAA** [comment]
Thanks @yukio-takeuchi. I haven't tested the changes yet, but they look good to me.

Here are a few minor changes that should be made to keep things working before merging this.
- [ ] add `#' @author Yukio Takeuchi` to the Roxygen2 comments at the top of `get_data_comments.r`
- [ ] run `devtools::document()` pointed to your local folder where this fork is located which should create `man/get_data_comments.Rd`

@k-doering-NOAA do you have any other suggestions before we merge these changes? Of course further refinements can be added as needed after merging.

**Comment by k-doering-NOAA** [comment]
Hi @yukio-takeuchi , I tested locally and reading and writing comments works as you described! Thank you for putting this together. A few questions/thoughts. I'm also happy to make any of these changes if that way is easiest for you (I believe I can push to your development fork), just let me know.

1. What do you think about calling `dataComments` just `comments` ? 
2.  What if the comments generated by SS_writectl and SS_readctl were read in, but not written out (upon writing, the lines would be updating to reflect the new read/write date and time)? I could imagne a scenario where someone would want to see this information in the comments, but if there is a good reason to not do this, I think the current way is fine!
3. Minor, but sapply can sometimes be tricky because it allows for different return types and may not error when it should (see http://adv-r.had.co.nz/Functionals.html) . Using vapply can be safer because return type is specified. If it is ok, can I change sapply to vapply? This can happen after merging in.

One last comment: super impressed by the regular expression for the first numeric value, good job figuring it out! :)

**Comment by yukio-takeuchi** [comment]
Hi @iantaylor-NOAA and @k-doering-NOAA  

Thank you for your comments.

OK, I will  add ``#' @author Yukio Takeuchi`` to the Roxygen2 comments at the top of get_data_comments.r and run devtools::document() pointed to your local folder where this fork is located which should create man/get_data_comments.Rd. Also I will follow the suggestion to call ``dataComments`` just ``comments`` ?  Also I am thinking of renaming ``get_data_comment`` function to ``get_comments``. Is it OK?

On the second point of @k-doering-NOAA,  SS_writedat_3.30 and SS_writectl_3.30 previously wrote "comments" with time stamp when those functions were called ignoring original time stamp of datfile and ctlfile they read.  My pull request employed strategy,
1. If datfile and/or ctlfile written by previous SS_writedat/ctl_3.30 is read, SS_writedat/ctl_3.30 will behave similarly to the previous SS_writedat/ctl_3.30 as for "comments", i.e., updating time stamp to the date and time when SS_writedat/ctl_3.30 were called and writing time stamp with header.
2. If there are  comments not by SS_writedat/ctl_3.30, they will be kept. 

Nevertheless, as for the 1st point, I have no particular opinion. If it is agreed  to keep all the lines of "comments" including time stamp, It also has a merit to make get_data_comments function simpler. In the case of data_ss.new and control_ss.new writtenn by SS, All the comments will be kept from datfile and ctlfile SS read.   

I am working to reflect suggestions I received to updated PR. When conclusion of 2nd point of @k-doering-NOAA  I will make an updated PR.

As for the 3rd point of @k-doering-NOAA,  I am not familiar with ``vsapply`` .  I just started to read the material @k-doering-NOAA  pointed out.  I would like to ask @k-doering-NOAA to change from sapply to vsapply after PR is merged.

**Comment by yukio-takeuchi** [comment]
What do you think the following alternative,
1.  keep all lines of "comments", when SS_readdat/ctl_3.30 read dat/ctlfile 
2. Add one more argument of SS_writedat/ctl_3.30. e.g "update_time_stamp" as logical. If update_time_stamp is TRUE, SS_writedat/ctl_3.30 will behave similar to current version (updating header comments and time stamp if comments contains header comments and time stamp made by SS_writedat/ctl_3.30).  If it is FALSE, all the comments will be written as they are.

**Comment by k-doering-NOAA** [comment]
Hi @yukio-takeuchi thanks for taking another look at this! My responses below:

>Also I will follow the suggestion to call dataComments just comments ? Also I am thinking of renaming get_data_comment function to get_comments. Is it OK?

Sounds good to me! I think once this has been changed,this PR will be ready to merge in!

>As for the 3rd point of @k-doering-NOAA, I am not familiar with vsapply . I just started to read the material @k-doering-NOAA pointed out. I would like to ask @k-doering-NOAA to change from sapply to vsapply after PR is merged.

Ok, I will do this after merging.

> What do you think the following alternative,
> 
> 1. keep all lines of "comments", when SS_readdat/ctl_3.30 read dat/ctlfile
> 2. Add one more argument of SS_writedat/ctl_3.30. e.g "update_time_stamp" as logical. If update_time_stamp is TRUE, SS_writedat/ctl_3.30 will behave similar to current version (updating header comments and time stamp if comments contains header comments and time stamp made by SS_writedat/ctl_3.30).  If it is FALSE, all the comments will be written as they are.

On second thought, it seems fine to leave as it has been implemented - we can always add the additional argument later if someone finds it helpful. Thanks for being open to ideas!

**Comment by k-doering-NOAA** [comment]
Thanks @yukio-takeuchi , looks good and works as described! I pushed a small change to get rid of a few remaining `dataComments` mentions and also got rid of the `#C should work with SS version:` line in the data file header that is written if `Comments` are null, which doesn't seem necessary (although I think it may have been helpful historically).

I think this is good to merge in if the tests pass.

**Pull request merged**
