### PR TITLE
Remove faster from tests; deprecate echoall argument in SS_readdat* functions

### PR DESCRIPTION
**Pull request by k-doering-NOAA**
Addresses #678. Also extends work done in #671, which included deprecating unneeded arguments in the read/write functions. For some reason, the echoall argument was not removed from the SS_readdat* functions, so it is done in this pull request

### CODE REVIEW

**Review by kellijohnson-NOAA — APPROVED** [review]
I am just wondering if we there are some calls that were printed to the screen with echoall that should maybe not be moved over to verbose? It just seems like an overwhelming amount of information is now printed to the screen where it was already a lot before.

**Comment by kellijohnson-NOAA** [comment]
Thanks for the background @iantaylor-NOAA. I agree with removing all the old output from echoall and leaving verbose to show the progress of the function and allow users to preview summaries that they might not know about. That is, I do not think there is a lot of utility in printing read in data like the catches to the screen.

**Comment by k-doering-NOAA** [comment]
@kellijohnson-NOAA , does this look better? For SS_readdat_3.30, I also took the time to refine the verbose msgs a bit to reflect their intended purpose (helping users track the function running, rather than printing output to the screen)

Also, IDK if we want to bump the version (just the patch?) relative to the main branch before merging in? Feel free to push a commit to do this, or I can - I should also bump the version on the lifecycle deprecation msg, too, fi that is the case.

**Comment by kellijohnson-NOAA** [comment]
This looks great @k-doering-NOAA feel free to merge in whenever you are ready.

**Pull request merged**
