### PR TITLE
Fix for hermaphroditism plots and generalize area colors

### PR DESCRIPTION
**Pull request by iantaylor-NOAA**
@e-gugliotti-NOAA, I tested this on a 3.30.20 model and a 3.30.21 model, but I think it would be helpful to have you look through the changes to the code to see if you catch any silly errors. It should only impact models with hermaphroditism, and probably within that only models with male to female transitions or multiple areas.

### CODE REVIEW

**Comment by e-gugliotti-NOAA** [comment]
@iantaylor-NOAA can you share the stock synthesis files you used to test this?

**Comment by e-gugliotti-NOAA** [comment]
@iantaylor-NOAA the plots are showing up and the fraction females by age plot is by area so I think that everything is good to go.

**Review by e-gugliotti-NOAA — APPROVED** [review]
This all looks good to me. Everything ran fine on my computer and the plot had sex ratio by area.

**Comment by iantaylor-NOAA** [comment]
Thank you @e-gugliotti-NOAA!

**Pull request merged**
