### PR TITLE
Depl basis plot

### PR DESCRIPTION
**Pull request by k-doering-NOAA**
Thanks @chantelwetzel-noaa for providing fixes in this branch that corrects the denominator in the relative SSB plots.

I suggest this be merged into main, unless you are planning to make more commits to the branch in the short term (feel free to close this PR if you would rather this code not be merged into main yet).

### CODE REVIEW

**Comment by chantelwetzel-noaa** [comment]
@k-doering-NOAA Thank you for following up on this.  I had not yet submitted a merge request since the fraction unfished plot when alternative denominators are requested (e.g, SBmsy, 0.50) for multi-area models has not been fixed yet.  The function works but creates non-sensical figures for fraction unfished without uncertainty.  The code in the main branch has a similar issue, so it does result in a degradation of performance but is still not 100%. If the team (@iantaylor-NOAA and @kellijohnson-NOAA ) are comfortable with merging this branch as-is then I will go ahead and do the review and merge.

**Comment by k-doering-NOAA** [comment]
Thanks @chantelwetzel-noaa ! I only saw your discussion with Ian after submitting the PR.

My opinion is if something is better than main and fixing the whole problem may not happen for a while (not sure if this is the case or not!), merging the partial solution earlier is better then waiting (you could even add a warning about the problem, if it seems quick to do and the solution won't happen for a while).

  But, I agree, I'm happy to defer to what @kellijohnson-NOAA  and @iantaylor-NOAA  think.

Thanks again for your work on this! It was great to be able to get help with #566

**Comment by iantaylor-NOAA** [comment]
I can take a little time today to look at what would be required for multi-area models and add to the documentation. If I'm not able to make quick progress I'll add a warning instead and go ahead and merge what we have.

**Comment by iantaylor-NOAA** [comment]
Plots for multi-area models are fine when the depletion basis is relative to B0. In other cases, the axis label needs changing, but I think the plot is still OK. Cases of multi-area models with relative spawning output related to Bmsy are surely few enough that it's better to just merge and get this working for the larger set of single area models and I'll open a separate issue to track fixes to the rare cases that still need work.

**Pull request merged**
